CREATE TABLE products(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL,
	PRIMARY KEY(id, name)
)ENGINE=INNODB;

CREATE TABLE customers(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL,
	PRIMARY KEY(id, name)
)ENGINE=INNODB;

CREATE TABLE orders(
	order_id INT NOT NULL AUTO_INCREMENT,
	oID INT NOT NULL,
	oName VARCHAR(30) NOT NULL,
	cID INT NOT NULL,
	cName VARCHAR(30) NOT NULL,
	INDEX(oID, oName),
	INDEX(cID, cName),
	FOREIGN KEY(oID, oName)
	REFERENCES products(id, name),
	FOREIGN KEY(cID, cName)
	REFERENCES customers(id, name),
	PRIMARY KEY(order_id)
)ENGINE=INNODB;